export enum FetchServerWithAuthWrapperEndPoint {
  LIST_USER_OWN_REPO = "list_user_own_repo",
  LIST_USER_LIKE_REPO = "list_user_like_repo",
  LIST_FOLLOWER = "list_follower",
  LIST_FOLLOWING = "list_following",

  GET_FOLLOER_COUNT = "get_follower_count",
  GET_FOLLOWING_COUNT = "get_following_count",
  GET_LIST_USER_OWN_REPO_COUNT = "get_list_user_own_repo_count",
  GET_LIST_USER_LIKE_REPO_COUNT = "get_list_user_like_repo_count",

  GET_LIST_USER_COUNT = "get_list_user_count",
  GET_LIST_SESSION_COUNT = "get_list_session_count",
  GET_LIST_COMMENT_REPORT_COUNT = "get_list_comment_report_count",
  GET_LIST_COMMENT_COUNT = "get_list_comment_count",
  GET_LIST_REPO_COUNT = "get_list_repo_count",
  DAILY_VISITOR_COUNT = "get_daily_visitor_count",
  DAILY_ACTIVE_USER_COUNT = "get_daily_active_user_count",
  DAILY_CREATE_USER_COUNT = "get_daily_create_user_count",

  LIST_USER = "list_user",
  LIST_SESSION = "list_session",
  LIST_COMMENT_REPORT = "list_comment_report",
  LIST_COMMENT = "list_comment",
  LIST_REPO = "list_repo",

  LIST_SELECTED_USER_BY_REPO = "list_selected_user_by_repo",
  QUERY_USER_BY_REPO = "query_user_by_repo",
  GET_SELECTED_USER_BY_REPO_COUNT = "get_selected_user_by_repo_count",

  GET_USER_INFO = "get_user_info",

  GET_REPO_BASIC_INFO = "get_repo_basic_info",
  GET_REPO_CONFIG = "get_repo_config",

  GET_MARKDOWN_CONTENT = "get_markdown_content",
  GET_MARKDOWN_IMAGE = "get_markdown_image",
  UPDATE_USER_BLOCK = "update_user_block",
  CREATE_REPO = "create_repo",
  UPDATE_USER = "update_user",

  CREATE_REPO_RELATION = "create_repo_relation",
  DELETE_REPO_RELATION = "delete_repo_relation",
  CREATE_REPO_VISIBILITY = "create_repo_visibility",
  DELETE_REPO_VISIBILITY = "delete_repo_visibility",
  LIST_FOLLOWER_NOTIFICATION = "list_follower_notification",
  LIST_REPO_NOTIFICATION = "list_repo_notification",
  LIST_COMMENT_NOTIFICATION = "list_comment_notification",
  LIST_SYSTEM_NOTIFICATION = "list_system_notification",

  GET_LIST_FOLLOWER_NOTIFICATION_UNREADED_COUNT = "get_list_follower_notification_unreaded_count",
  GET_LIST_REPO_NOTIFICATION_UNREADED_COUNT = "get_list_repo_notification_unreaded_count",
  GET_LIST_COMMENT_NOTIFICATION_UNREADED_COUNT = "get_list_comment_notification_unreaded_count",
  GET_LIST_SYSTEM_NOTIFICATION_UNREADED_COUNT = "get_list_system_notification_unreaded_count",

  LIST_COMMENT_LEVEL_ONE = "list_comment_level_one",
  LIST_COMMENT_LEVEL_TWO = "list_comment_level_two",
  GET_LIST_COMMENT_LEVEL_ONE_COUNT = "get_list_comment_level_one_count",
  GET_LIST_COMMENT_LEVEL_TWO_COUNT = "get_list_comment_level_two_count",
  MARK_FOLLOWER_NOTI_READED = "mark_follower_notification_readed",
  MARK_REPO_NOTI_READED = "mark_repo_notification_readed",
  MARK_COMMENT_NOTI_READED = "mark_comment_notification_readed",
  MARK_SYSTEM_NOTI_READED = "mark_system_notification_readed",
  UPDATE_COMMENT_REPORT_STATUS = "update_comment_report_status",
  CREATE_SYSTEM_NOTIFICATION = "create_system_notification",
  DELETE_REPO = "delete_repo",
  DELETE_USER = "delete_user",
  DELETE_COMMENT = "delete_comment",
  CREATE_COMMENT = "create_comment",
  CREATE_COMMENT_REPORT = "create_comment_report",
  CREATE_COMMENT_RELATION = "create_comment_relation",
  DELETE_COMMENT_RELATION = "delete_comment_relation",
  GET_COMMENT_COUNT_INFO = "get_comment_count_info",
  QUERY_USER_MARKDOWN = "query_user_markdown",
  QUERY_MARKDOWN = "query_markdown",
  QUERY_REPO_MARKDOWN = "query_repo_markdown",
  RESET_UNREAD_COUNT = "reset_unread_count",
  GET_UNREAD_COUNT = "get_unread_count",
  MANUAL_SYNC_REPO = "manual_sync_repo",
  UPDATE_REPO_INFO = "update_repo_info",

  CHECK_OAUTH_STATUS = "check_oauth_status",
  DELETE_OAUTH_LINK = "delete_oauth_link",

  QUERY_USER = "query_user",
  CREATE_FOLLOW = "create_follow",
  DELETE_FOLLOW = "delete_follow",
  GET_FOLLOWE_STATUS = "get_follow_status",
  UPDATE_USER_ONBOARDING = "update_user_onboarding",
  GetDailyVisitors = "get_daily_visitors",
  GetConfiguration = "get_configuration",
  UpdateConfiguration = "update_configuration",
  CreateInvitation = "create_invitation",
}
