// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: rpcs/rpc_notification.proto

package rpcs

import (
	models "github.com/zizdlp/zbook/pb/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1.ListFollowerNotification
type ListFollowerNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageId   int32 `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListFollowerNotificationRequest) Reset() {
	*x = ListFollowerNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFollowerNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowerNotificationRequest) ProtoMessage() {}

func (x *ListFollowerNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowerNotificationRequest.ProtoReflect.Descriptor instead.
func (*ListFollowerNotificationRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ListFollowerNotificationRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListFollowerNotificationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFollowerNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notifications []*models.ListFollowerNotificationInfo `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *ListFollowerNotificationResponse) Reset() {
	*x = ListFollowerNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFollowerNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowerNotificationResponse) ProtoMessage() {}

func (x *ListFollowerNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowerNotificationResponse.ProtoReflect.Descriptor instead.
func (*ListFollowerNotificationResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ListFollowerNotificationResponse) GetNotifications() []*models.ListFollowerNotificationInfo {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// 2.ListRepoNotification
type ListRepoNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageId   int32 `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListRepoNotificationRequest) Reset() {
	*x = ListRepoNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRepoNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepoNotificationRequest) ProtoMessage() {}

func (x *ListRepoNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepoNotificationRequest.ProtoReflect.Descriptor instead.
func (*ListRepoNotificationRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ListRepoNotificationRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListRepoNotificationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRepoNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notifications []*models.ListRepoNotificationInfo `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *ListRepoNotificationResponse) Reset() {
	*x = ListRepoNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRepoNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepoNotificationResponse) ProtoMessage() {}

func (x *ListRepoNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepoNotificationResponse.ProtoReflect.Descriptor instead.
func (*ListRepoNotificationResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ListRepoNotificationResponse) GetNotifications() []*models.ListRepoNotificationInfo {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// 3.ListCommentNotification
type ListCommentNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageId   int32 `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListCommentNotificationRequest) Reset() {
	*x = ListCommentNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentNotificationRequest) ProtoMessage() {}

func (x *ListCommentNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentNotificationRequest.ProtoReflect.Descriptor instead.
func (*ListCommentNotificationRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ListCommentNotificationRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListCommentNotificationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCommentNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notifications []*models.ListCommentNotificationInfo `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *ListCommentNotificationResponse) Reset() {
	*x = ListCommentNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCommentNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentNotificationResponse) ProtoMessage() {}

func (x *ListCommentNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentNotificationResponse.ProtoReflect.Descriptor instead.
func (*ListCommentNotificationResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListCommentNotificationResponse) GetNotifications() []*models.ListCommentNotificationInfo {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// 4.ListSystemNotification
type ListSystemNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageId   int32 `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListSystemNotificationRequest) Reset() {
	*x = ListSystemNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSystemNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemNotificationRequest) ProtoMessage() {}

func (x *ListSystemNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemNotificationRequest.ProtoReflect.Descriptor instead.
func (*ListSystemNotificationRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListSystemNotificationRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListSystemNotificationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSystemNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notifications []*models.ListSystemNotificationInfo `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *ListSystemNotificationResponse) Reset() {
	*x = ListSystemNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSystemNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemNotificationResponse) ProtoMessage() {}

func (x *ListSystemNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemNotificationResponse.ProtoReflect.Descriptor instead.
func (*ListSystemNotificationResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{7}
}

func (x *ListSystemNotificationResponse) GetNotifications() []*models.ListSystemNotificationInfo {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// 5.MarkFollowerNotificationReaded
type MarkFollowerNotificationReadedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotiId int64 `protobuf:"varint,1,opt,name=noti_id,json=notiId,proto3" json:"noti_id,omitempty"`
}

func (x *MarkFollowerNotificationReadedRequest) Reset() {
	*x = MarkFollowerNotificationReadedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkFollowerNotificationReadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFollowerNotificationReadedRequest) ProtoMessage() {}

func (x *MarkFollowerNotificationReadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFollowerNotificationReadedRequest.ProtoReflect.Descriptor instead.
func (*MarkFollowerNotificationReadedRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{8}
}

func (x *MarkFollowerNotificationReadedRequest) GetNotiId() int64 {
	if x != nil {
		return x.NotiId
	}
	return 0
}

// 6.MarkSystemNotificationReaded
type MarkSystemNotificationReadedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotiId int64 `protobuf:"varint,1,opt,name=noti_id,json=notiId,proto3" json:"noti_id,omitempty"`
}

func (x *MarkSystemNotificationReadedRequest) Reset() {
	*x = MarkSystemNotificationReadedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkSystemNotificationReadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkSystemNotificationReadedRequest) ProtoMessage() {}

func (x *MarkSystemNotificationReadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkSystemNotificationReadedRequest.ProtoReflect.Descriptor instead.
func (*MarkSystemNotificationReadedRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{9}
}

func (x *MarkSystemNotificationReadedRequest) GetNotiId() int64 {
	if x != nil {
		return x.NotiId
	}
	return 0
}

// 7.MarkCommentNotificationReaded
type MarkCommentNotificationReadedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotiId int64 `protobuf:"varint,1,opt,name=noti_id,json=notiId,proto3" json:"noti_id,omitempty"`
}

func (x *MarkCommentNotificationReadedRequest) Reset() {
	*x = MarkCommentNotificationReadedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkCommentNotificationReadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCommentNotificationReadedRequest) ProtoMessage() {}

func (x *MarkCommentNotificationReadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCommentNotificationReadedRequest.ProtoReflect.Descriptor instead.
func (*MarkCommentNotificationReadedRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{10}
}

func (x *MarkCommentNotificationReadedRequest) GetNotiId() int64 {
	if x != nil {
		return x.NotiId
	}
	return 0
}

// 8.MarkRepoNotificationReaded
type MarkRepoNotificationReadedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotiId int64 `protobuf:"varint,1,opt,name=noti_id,json=notiId,proto3" json:"noti_id,omitempty"`
}

func (x *MarkRepoNotificationReadedRequest) Reset() {
	*x = MarkRepoNotificationReadedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkRepoNotificationReadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRepoNotificationReadedRequest) ProtoMessage() {}

func (x *MarkRepoNotificationReadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRepoNotificationReadedRequest.ProtoReflect.Descriptor instead.
func (*MarkRepoNotificationReadedRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{11}
}

func (x *MarkRepoNotificationReadedRequest) GetNotiId() int64 {
	if x != nil {
		return x.NotiId
	}
	return 0
}

type SetNotiReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetNotiReadResponse) Reset() {
	*x = SetNotiReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNotiReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNotiReadResponse) ProtoMessage() {}

func (x *SetNotiReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNotiReadResponse.ProtoReflect.Descriptor instead.
func (*SetNotiReadResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{12}
}

// 9.GetUnReadCount
type GetUnReadCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUnReadCountRequest) Reset() {
	*x = GetUnReadCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnReadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnReadCountRequest) ProtoMessage() {}

func (x *GetUnReadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnReadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnReadCountRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{13}
}

type GetUnReadCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnreadCount int32 `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
}

func (x *GetUnReadCountResponse) Reset() {
	*x = GetUnReadCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnReadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnReadCountResponse) ProtoMessage() {}

func (x *GetUnReadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnReadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnReadCountResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{14}
}

func (x *GetUnReadCountResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// 10.ResetUnreadCount
type ResetUnreadCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetUnreadCountRequest) Reset() {
	*x = ResetUnreadCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUnreadCountRequest) ProtoMessage() {}

func (x *ResetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*ResetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{15}
}

type ResetUnreadCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetUnreadCountResponse) Reset() {
	*x = ResetUnreadCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUnreadCountResponse) ProtoMessage() {}

func (x *ResetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*ResetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{16}
}

// 11.GetListFollowerNotificationUnreadedCount
type GetListFollowerNotificationUnreadedCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListFollowerNotificationUnreadedCountRequest) Reset() {
	*x = GetListFollowerNotificationUnreadedCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListFollowerNotificationUnreadedCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListFollowerNotificationUnreadedCountRequest) ProtoMessage() {}

func (x *GetListFollowerNotificationUnreadedCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListFollowerNotificationUnreadedCountRequest.ProtoReflect.Descriptor instead.
func (*GetListFollowerNotificationUnreadedCountRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{17}
}

type GetListFollowerNotificationUnreadedCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetListFollowerNotificationUnreadedCountResponse) Reset() {
	*x = GetListFollowerNotificationUnreadedCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListFollowerNotificationUnreadedCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListFollowerNotificationUnreadedCountResponse) ProtoMessage() {}

func (x *GetListFollowerNotificationUnreadedCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListFollowerNotificationUnreadedCountResponse.ProtoReflect.Descriptor instead.
func (*GetListFollowerNotificationUnreadedCountResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{18}
}

func (x *GetListFollowerNotificationUnreadedCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 12.GetListRepoNotificationUnreadedCount
type GetListRepoNotificationUnreadedCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListRepoNotificationUnreadedCountRequest) Reset() {
	*x = GetListRepoNotificationUnreadedCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListRepoNotificationUnreadedCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRepoNotificationUnreadedCountRequest) ProtoMessage() {}

func (x *GetListRepoNotificationUnreadedCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRepoNotificationUnreadedCountRequest.ProtoReflect.Descriptor instead.
func (*GetListRepoNotificationUnreadedCountRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{19}
}

type GetListRepoNotificationUnreadedCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetListRepoNotificationUnreadedCountResponse) Reset() {
	*x = GetListRepoNotificationUnreadedCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListRepoNotificationUnreadedCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRepoNotificationUnreadedCountResponse) ProtoMessage() {}

func (x *GetListRepoNotificationUnreadedCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRepoNotificationUnreadedCountResponse.ProtoReflect.Descriptor instead.
func (*GetListRepoNotificationUnreadedCountResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{20}
}

func (x *GetListRepoNotificationUnreadedCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 13.GetListCommentNotificationUnreadedCount
type GetListCommentNotificationUnreadedCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListCommentNotificationUnreadedCountRequest) Reset() {
	*x = GetListCommentNotificationUnreadedCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListCommentNotificationUnreadedCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListCommentNotificationUnreadedCountRequest) ProtoMessage() {}

func (x *GetListCommentNotificationUnreadedCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListCommentNotificationUnreadedCountRequest.ProtoReflect.Descriptor instead.
func (*GetListCommentNotificationUnreadedCountRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{21}
}

type GetListCommentNotificationUnreadedCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetListCommentNotificationUnreadedCountResponse) Reset() {
	*x = GetListCommentNotificationUnreadedCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListCommentNotificationUnreadedCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListCommentNotificationUnreadedCountResponse) ProtoMessage() {}

func (x *GetListCommentNotificationUnreadedCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListCommentNotificationUnreadedCountResponse.ProtoReflect.Descriptor instead.
func (*GetListCommentNotificationUnreadedCountResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{22}
}

func (x *GetListCommentNotificationUnreadedCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 14.GetListSystemNotificationUnreadedCount
type GetListSystemNotificationUnreadedCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListSystemNotificationUnreadedCountRequest) Reset() {
	*x = GetListSystemNotificationUnreadedCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListSystemNotificationUnreadedCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListSystemNotificationUnreadedCountRequest) ProtoMessage() {}

func (x *GetListSystemNotificationUnreadedCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListSystemNotificationUnreadedCountRequest.ProtoReflect.Descriptor instead.
func (*GetListSystemNotificationUnreadedCountRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{23}
}

type GetListSystemNotificationUnreadedCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetListSystemNotificationUnreadedCountResponse) Reset() {
	*x = GetListSystemNotificationUnreadedCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_rpc_notification_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListSystemNotificationUnreadedCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListSystemNotificationUnreadedCountResponse) ProtoMessage() {}

func (x *GetListSystemNotificationUnreadedCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_rpc_notification_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListSystemNotificationUnreadedCountResponse.ProtoReflect.Descriptor instead.
func (*GetListSystemNotificationUnreadedCountResponse) Descriptor() ([]byte, []int) {
	return file_rpcs_rpc_notification_proto_rawDescGZIP(), []int{24}
}

func (x *GetListSystemNotificationUnreadedCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_rpcs_rpc_notification_proto protoreflect.FileDescriptor

var file_rpcs_rpc_notification_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x19, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x1f,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x6a, 0x0a, 0x20, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x53, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x62, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x56, 0x0a, 0x1e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x22, 0x68, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x55, 0x0a, 0x1d,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x66, 0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x40, 0x0a, 0x25, 0x4d,
	0x61, 0x72, 0x6b, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x69, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x49, 0x64, 0x22, 0x3e, 0x0a,
	0x23, 0x4d, 0x61, 0x72, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x69, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x49, 0x64, 0x22, 0x3f, 0x0a,
	0x24, 0x4d, 0x61, 0x72, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x69, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x49, 0x64, 0x22, 0x3c,
	0x0a, 0x21, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x69, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13,
	0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x52, 0x65, 0x61, 0x64,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x55, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x75, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x73, 0x65, 0x74, 0x55, 0x6e, 0x72,
	0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x31, 0x0a, 0x2f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x30, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2d, 0x0a,
	0x2b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x65, 0x64,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x2c,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x65, 0x64, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x30, 0x0a, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x2f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2f, 0x0a,
	0x2d, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64,
	0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x46,
	0x0a, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x69, 0x7a, 0x64, 0x6c, 0x70, 0x2f, 0x7a, 0x62, 0x6f, 0x6f,
	0x6b, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rpcs_rpc_notification_proto_rawDescOnce sync.Once
	file_rpcs_rpc_notification_proto_rawDescData = file_rpcs_rpc_notification_proto_rawDesc
)

func file_rpcs_rpc_notification_proto_rawDescGZIP() []byte {
	file_rpcs_rpc_notification_proto_rawDescOnce.Do(func() {
		file_rpcs_rpc_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcs_rpc_notification_proto_rawDescData)
	})
	return file_rpcs_rpc_notification_proto_rawDescData
}

var file_rpcs_rpc_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_rpcs_rpc_notification_proto_goTypes = []interface{}{
	(*ListFollowerNotificationRequest)(nil),                  // 0: pb.ListFollowerNotificationRequest
	(*ListFollowerNotificationResponse)(nil),                 // 1: pb.ListFollowerNotificationResponse
	(*ListRepoNotificationRequest)(nil),                      // 2: pb.ListRepoNotificationRequest
	(*ListRepoNotificationResponse)(nil),                     // 3: pb.ListRepoNotificationResponse
	(*ListCommentNotificationRequest)(nil),                   // 4: pb.ListCommentNotificationRequest
	(*ListCommentNotificationResponse)(nil),                  // 5: pb.ListCommentNotificationResponse
	(*ListSystemNotificationRequest)(nil),                    // 6: pb.ListSystemNotificationRequest
	(*ListSystemNotificationResponse)(nil),                   // 7: pb.ListSystemNotificationResponse
	(*MarkFollowerNotificationReadedRequest)(nil),            // 8: pb.MarkFollowerNotificationReadedRequest
	(*MarkSystemNotificationReadedRequest)(nil),              // 9: pb.MarkSystemNotificationReadedRequest
	(*MarkCommentNotificationReadedRequest)(nil),             // 10: pb.MarkCommentNotificationReadedRequest
	(*MarkRepoNotificationReadedRequest)(nil),                // 11: pb.MarkRepoNotificationReadedRequest
	(*SetNotiReadResponse)(nil),                              // 12: pb.SetNotiReadResponse
	(*GetUnReadCountRequest)(nil),                            // 13: pb.GetUnReadCountRequest
	(*GetUnReadCountResponse)(nil),                           // 14: pb.GetUnReadCountResponse
	(*ResetUnreadCountRequest)(nil),                          // 15: pb.ResetUnreadCountRequest
	(*ResetUnreadCountResponse)(nil),                         // 16: pb.ResetUnreadCountResponse
	(*GetListFollowerNotificationUnreadedCountRequest)(nil),  // 17: pb.GetListFollowerNotificationUnreadedCountRequest
	(*GetListFollowerNotificationUnreadedCountResponse)(nil), // 18: pb.GetListFollowerNotificationUnreadedCountResponse
	(*GetListRepoNotificationUnreadedCountRequest)(nil),      // 19: pb.GetListRepoNotificationUnreadedCountRequest
	(*GetListRepoNotificationUnreadedCountResponse)(nil),     // 20: pb.GetListRepoNotificationUnreadedCountResponse
	(*GetListCommentNotificationUnreadedCountRequest)(nil),   // 21: pb.GetListCommentNotificationUnreadedCountRequest
	(*GetListCommentNotificationUnreadedCountResponse)(nil),  // 22: pb.GetListCommentNotificationUnreadedCountResponse
	(*GetListSystemNotificationUnreadedCountRequest)(nil),    // 23: pb.GetListSystemNotificationUnreadedCountRequest
	(*GetListSystemNotificationUnreadedCountResponse)(nil),   // 24: pb.GetListSystemNotificationUnreadedCountResponse
	(*models.ListFollowerNotificationInfo)(nil),              // 25: pb.ListFollowerNotificationInfo
	(*models.ListRepoNotificationInfo)(nil),                  // 26: pb.ListRepoNotificationInfo
	(*models.ListCommentNotificationInfo)(nil),               // 27: pb.ListCommentNotificationInfo
	(*models.ListSystemNotificationInfo)(nil),                // 28: pb.ListSystemNotificationInfo
}
var file_rpcs_rpc_notification_proto_depIdxs = []int32{
	25, // 0: pb.ListFollowerNotificationResponse.notifications:type_name -> pb.ListFollowerNotificationInfo
	26, // 1: pb.ListRepoNotificationResponse.notifications:type_name -> pb.ListRepoNotificationInfo
	27, // 2: pb.ListCommentNotificationResponse.notifications:type_name -> pb.ListCommentNotificationInfo
	28, // 3: pb.ListSystemNotificationResponse.notifications:type_name -> pb.ListSystemNotificationInfo
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpcs_rpc_notification_proto_init() }
func file_rpcs_rpc_notification_proto_init() {
	if File_rpcs_rpc_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcs_rpc_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFollowerNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFollowerNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRepoNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRepoNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCommentNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSystemNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSystemNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkFollowerNotificationReadedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkSystemNotificationReadedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkCommentNotificationReadedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkRepoNotificationReadedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNotiReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnReadCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnReadCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetUnreadCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetUnreadCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListFollowerNotificationUnreadedCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListFollowerNotificationUnreadedCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListRepoNotificationUnreadedCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListRepoNotificationUnreadedCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListCommentNotificationUnreadedCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListCommentNotificationUnreadedCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListSystemNotificationUnreadedCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_rpc_notification_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListSystemNotificationUnreadedCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcs_rpc_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpcs_rpc_notification_proto_goTypes,
		DependencyIndexes: file_rpcs_rpc_notification_proto_depIdxs,
		MessageInfos:      file_rpcs_rpc_notification_proto_msgTypes,
	}.Build()
	File_rpcs_rpc_notification_proto = out.File
	file_rpcs_rpc_notification_proto_rawDesc = nil
	file_rpcs_rpc_notification_proto_goTypes = nil
	file_rpcs_rpc_notification_proto_depIdxs = nil
}
