name: BUILD_MAIN

on:
  push:
    branches:
      - feature/image_client
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [zbook_backend, zbook_database, zbook_frontend]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_TOKEN }}
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.service }}"
          file: ${{ matrix.service }}.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.PRIVATE_REGISTRY_URL }}/zbook/${{ matrix.service }}
