name: BUILD_MAIN

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [zbook_backend, zbook_database, zbook_frontend]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_TOKEN }}
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Install protoc-gen-go and other plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.10.0
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.10.0
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Install statik
        run: |
          go install github.com/rakyll/statik@latest
          export PATH=$PATH:$(go env GOPATH)/bin
      - name: Set up protobuf and statik files
        run: |
          if [ "${{ matrix.service }}" == "zbook_backend" ]; then
            cd zbook_backend && \
            mkdir -p pb && \
            rm -f -r statik/* && \
            rm -f -r pb/* &&  \
            rm -f -r doc/swagger/*  && \
            protoc --proto_path=proto --proto_path=proto/models --proto_path=proto/rpcs --go_out=pb --go_opt=paths=source_relative  \
            --go-grpc_out=pb --go-grpc_opt=paths=source_relative  \
            --grpc-gateway_out=pb \
            --openapiv2_out=doc/swagger \
            --grpc-gateway_opt paths=source_relative \
            proto/**/*.proto proto/*.proto && \
            statik -src=./doc -dest=./
          fi
      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.service }}"
          file: ${{ matrix.service }}.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.PRIVATE_REGISTRY_URL }}/zbook/${{ matrix.service }}
