name: BUILD_DATABASE

on:
  push:
    branches:
      - main
jobs:
  build_database:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_TOKEN }}
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
      - name: Build and push zbook_database
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:zbook_database"
          file: zbook_database.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.PRIVATE_REGISTRY_URL }}/zbook/zbook_database
