name: TEST_BACKEND

on:
  push:
    branches:
      - "debug/create2"
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: zizdlp/zbook_database
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: zbook
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          which migrate
      - name: Run migrations
        run: make migrateup
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version
      - name: Set up protobuf and statik files
        run: |
          cd zbook_backend && \
          mkdir -p pb && \
          rm -f -r statik/* && \
          rm -f -r pb/* &&  \
          rm -f -r doc/swagger/*  && \
          protoc  --proto_path=proto --proto_path=proto/models --proto_path=proto/rpcs --go_out=pb --go_opt=paths=source_relative  \
          --go-grpc_out=pb --go-grpc_opt=paths=source_relative  \
          --grpc-gateway_out=pb \
          --openapiv2_out=doc/swagger \
          --grpc-gateway_opt paths=source_relative \
          proto/**/*.proto proto/*.proto && \
          statik -src=./doc -dest=./

      - name: Test
        run: make test
